### ISSUE TITLE
User with owner access to org gets 403 forbidden

### ISSUE THREAD

**Issue by terrajobst** [octokit/octokit.graphql.net#238]
I have [the following query](https://github.com/dotnet/org-policy/blob/master/src/Microsoft.DotnetOrg.GitHubCaching/CacheLoader.cs#L395-L420):

```C#
            var query = new Query()
                .Repository(Var("repoName"), orgName)
                .Collaborators(first: 100, after: Var("after"), affiliation: CollaboratorAffiliation.Direct)
                .Select(connection => new
                {
                    connection.PageInfo.EndCursor,
                    connection.PageInfo.HasNextPage,
                    connection.TotalCount,
                    Items = connection.Edges.Select(e => new
                    {
                        e.Node.Login,
                        e.Permission,
                    }).ToList(),
                }).Compile();

            var result = new List<CachedUserAccess>();

            foreach (var repoName in repoNames)
            {
                var vars = new Dictionary<string, object>
                {
                    { "after", null },
                    { "repoName", repoName },
                };

                var current = await Connection.Run(query, vars);
```

that fails with

```
Unhandled Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
```

<details>
<summary>Full Exception</summary>

```text
Unhandled Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Octokit.GraphQL.Connection.<Run>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.GraphQL.Core.SimpleQuery`1.Runner.<RunPage>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Octokit.GraphQL.ConnectionExtensions.<Run>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.DotnetOrg.GitHubCaching.CacheLoader.<GetCachedTeamMembersAsync>d__14.MoveNext() in D:\a\1\s\src\Microsoft.DotnetOrg.GitHubCaching\CacheLoader.cs:line 194
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.DotnetOrg.GitHubCaching.CacheLoader.<LoadAsync>d__10.MoveNext() in D:\a\1\s\src\Microsoft.DotnetOrg.GitHubCaching\CacheLoader.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.DotnetOrg.PolicyCop.Commands.CacheOrgCommand.<ExecuteAsync>d__7.MoveNext() in D:\a\1\s\src\policop\Commands\CacheOrgCommand.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.DotnetOrg.PolicyCop.Program.<Main>d__0.MoveNext() in D:\a\1\s\src\policop\Program.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.DotnetOrg.PolicyCop.Program.<Main>(String[] args)
```

</details>

This error occurs in both the mono and xamarin orgs; However, the query succeeds in just fine in the orgs aspnet, dotnet, and xamarinhq. It's the same user in all cases and the user is an org owner in all orgs.

Any ideas?

**Comment by jcansdale** [comment]
Unfortunately I haven't been able to repro this because I don't have push access. 😢 

```
Octokit.GraphQL.Core.Deserializers.ResponseDeserializerException: Must have push access to view repository collaborators.
   at Octokit.GraphQL.Core.Deserializers.ResponseDeserializer.Deserialize[TResult](Func`2 deserialize, JObject data)
```

Any chance you could send up a repo with this running (and failing) as a workflow? 🙏

**Comment by terrajobst** [comment]
Unfortunately I can't repro this. Could you send me an email at immol at microsoft dot com? I can give you the necessary perms to repro this on our actual repo.s

**Comment by terrajobst** [comment]
It seems these are intermittent errors. Adding a re-try loop has pretty much solved this issue for me. Strange.
