### ISSUE TITLE
[BUG]: EnablePullRequestAutoMergeInput failing using v0.2.1-beta with GHES 3.8.4

### ISSUE THREAD

**Issue by martincostello** [octokit/octokit.graphql.net#302]
### What happened?

I updated an internal application using Octokit.GraphQL to `0.2.1-beta` from `0.2.0-beta` and now trying to enable auto-merge of pull request with GitHub Enterprise Server 3.8.4 fails with the following exception:

```
Octokit.GraphQL.Core.Deserializers.ResponseDeserializerException: InputObject 'EnablePullRequestAutoMergeInput' doesn't accept argument 'expectedHeadOid'
   at Octokit.GraphQL.Core.Deserializers.ResponseDeserializer.Deserialize[TResult](Func`2 deserialize, JObject data)
   at Octokit.GraphQL.Core.SimpleQuery`1.Runner.RunPage(CancellationToken cancellationToken)
   at Octokit.GraphQL.ConnectionExtensions.Run[T](IConnection connection, ICompiledQuery`1 query, Dictionary`2 variables, CancellationToken cancellationToken)
```

This appears to have been added by https://github.com/octokit/octokit.graphql.net/commit/3f5eaa072f3ac0498bcf0f28de914b5f83f29481#diff-cf7ac8c5e36ed6761cce0393cc816f53b1cb638369577d730bf568ead8b8ee6e.

### Versions

0.2.1-beta

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by martincostello** [comment]
I'm going to leave this open (unless fixed I guess it can be closed when GHES 3.8 goes out of support), but after upgrading to both the 0.3.0-beta package _and_ GitHub Enterprise 3.9 this specific issue is no longer affecting my application.
